server:
  port: 8082
    
# Oracle #
spring:
  datasource:
    url: jdbc:mysql://d6rii63wp64rsfb5.cbetxkdyhwsb.us-east-1.rds.amazonaws.com:3306/j5rh7he4sgm6izvq
    username: g5zzt5btgbdpnre1
    password: v0nmzyiyyoq5kr72
    driverClassName: com.mysql.cj.jdbc.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
    show-sql: true
    hibernate:
      ddl-auto: update
    open-in-view: false

