--SYSTEM
--CREATE USER dbbiblioteca IDENTIFIED BY abc123;
--GRANT ALL PRIVILEGES TO dbbiblioteca;
--GRANT UNLIMITED TABLESPACE TO dbbiblioteca;

CREATE TABLE TBL_CATEGORIAS(
    ID NUMERIC(4) NOT NULL PRIMARY KEY,
    NOMBRE VARCHAR2(50) NOT NULL,
    ESTADO CHAR(1) NOT NULL
);
CREATE SEQUENCE SEQ_CATEGORIAS;
CREATE TABLE TBL_AUTORES(
    ID NUMERIC(4) NOT NULL PRIMARY KEY,
    NOMBRES VARCHAR2(50) NOT NULL,
    APELLIDOS VARCHAR2(50) NOT NULL,
    PAIS VARCHAR2(20) NOT NULL,
    ESTADO CHAR(1) NOT NULL
);
CREATE SEQUENCE SEQ_AUTORES;
CREATE TABLE TBL_EDITORIALES(
    ID NUMERIC(4) NOT NULL PRIMARY KEY,
    NOMBRE VARCHAR2(50) NOT NULL,
    DIRECCION VARCHAR2(50) NOT NULL,
    ESTADO CHAR(1) NOT NULL
);
CREATE SEQUENCE SEQ_EDITORIALES;
CREATE TABLE TBL_ROLES(
    ID NUMERIC(4) NOT NULL PRIMARY KEY,
    NOMBRE VARCHAR2(50) NOT NULL,
    ESTADO CHAR(1) NOT NULL
);
CREATE SEQUENCE SEQ_ROLES;
CREATE TABLE TBL_LECTORES(
    ID NUMERIC(4) NOT NULL PRIMARY KEY,
    NOMBRES VARCHAR2(50) NOT NULL,
    APELLIDOS VARCHAR2(50) NOT NULL,
    DNI NUMERIC(8) NOT NULL,
    TELEFONO NUMERIC(9) NOT NULL,
    DIRECCION VARCHAR2(50) NOT NULL,
    ESTADO CHAR(1) NOT NULL
);
CREATE SEQUENCE SEQ_LECTORES;
CREATE TABLE TBL_EMPLEADOS(
    ID NUMERIC(4) NOT NULL PRIMARY KEY,
    NOMBRES VARCHAR2(50) NOT NULL,
    APELLIDOS VARCHAR2(50) NOT NULL,
    DNI NUMERIC(8) NOT NULL,
    TELEFONO NUMERIC(9) NOT NULL,
    ESTADO CHAR(1) NOT NULL
);
CREATE SEQUENCE SEQ_EMPLEADOS;
CREATE TABLE TBL_SECCIONES(
    ID            NUMERIC(4) NOT NULL PRIMARY KEY,
    SECCION       VARCHAR2(20) NOT NULL UNIQUE,
    ESTADO CHAR(1) NOT NULL,
    CATEGORIA_ID NUMERIC(4) REFERENCES TBL_CATEGORIAS(ID)
 );
 CREATE SEQUENCE SEQ_SECCIONES;
 CREATE TABLE TBL_LIBROS(
    ID            NUMERIC(4) NOT NULL PRIMARY KEY,
    TITULO       VARCHAR2(20) NOT NULL UNIQUE,
    PAGINAS       NUMERIC(4) NOT NULL,
    EDICION       VARCHAR2(20) NULL,
    ESTADO CHAR(1) NOT NULL,
    SECCION_ID NUMERIC(4) REFERENCES TBL_SECCIONES(ID)
 );
 CREATE SEQUENCE SEQ_LIBROS;
 CREATE TABLE TBL_USUARIOS(
    ID            NUMERIC(4) NOT NULL PRIMARY KEY,
    USERNAME       VARCHAR2(20) NOT NULL UNIQUE,
    PASSWORD       VARCHAR2(100) NOT NULL,
    ESTADO CHAR(1) NOT NULL,
    EMPLEADO_ID NUMERIC(4) REFERENCES TBL_EMPLEADOS(ID)
 );
 CREATE SEQUENCE SEQ_USUARIOS;
  CREATE TABLE TBL_PRESTAMOS(
    ID NUMERIC(4) NOT NULL PRIMARY KEY,
    FECHA_PRESTAMO TIMESTAMP NOT NULL,
    FECHA_ENTREGA DATE NOT NULL,
    ESTADO CHAR(1) NOT NULL,
    LECTOR_ID NUMERIC(4) REFERENCES TBL_LECTORES(ID),
    USUARIO_ID NUMERIC(4) REFERENCES TBL_USUARIOS(ID)
 );
 CREATE SEQUENCE SEQ_PRESTAMOS;
 CREATE TABLE TBL_DETALLE_PRESTAMOS(
    ID NUMERIC(4) NOT NULL PRIMARY KEY,
    ESTADO CHAR(1) NOT NULL,
    PRESTAMO_ID NUMERIC(4) REFERENCES TBL_PRESTAMOS(ID),
    LIBRO_ID NUMERIC(4) REFERENCES TBL_LIBROS(ID)
 );
 CREATE SEQUENCE SEQ_DETALLE_PRESTAMOS;
CREATE TABLE TBL_USUARIO_ROL(
USUARIO_ID NUMERIC(4) REFERENCES TBL_USUARIOS(ID),
ROL_ID NUMERIC(4) REFERENCES TBL_ROLES(ID)
)
CREATE TABLE TBL_EDITORIAL_LIBRO(
EDITORIAL_ID NUMERIC(4) REFERENCES TBL_EDITORIALES(ID),
LIBRO_ID NUMERIC(4) REFERENCES TBL_LIBROS(ID)
)
CREATE TABLE TBL_LIBRO_AUTOR(
LIBRO_ID NUMERIC(4) REFERENCES TBL_LIBROS(ID),
AUTOR_ID NUMERIC(4) REFERENCES TBL_AUTORES(ID)
)
CREATE TABLE TBL_LIBRO_PRESTAMO(
OBSERVACIONES VARCHAR2(50) NULL,
FECHA_ENTREGA DATE NOT NULL,
ESTADO CHAR(1) NOT NULL,
LIBRO_ID NUMERIC(4) REFERENCES TBL_LIBROS(ID),
PRESTAMO_ID NUMERIC(4) REFERENCES TBL_PRESTAMOS(ID)
)
 